name: phylogenetics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  - biopython
  - mafft
  - phykit
  - clipkit
  - modeltest-ng
  - raxml-ng
  - iqtree
  - pip
  - numpy
  - scipy
  - scikit-learn
